
package publicar;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "InstanciaNoExiste", targetNamespace = "http://publicar/")
public class InstanciaNoExiste_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InstanciaNoExiste faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public InstanciaNoExiste_Exception(String message, InstanciaNoExiste faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public InstanciaNoExiste_Exception(String message, InstanciaNoExiste faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: publicar.InstanciaNoExiste
     */
    public InstanciaNoExiste getFaultInfo() {
        return faultInfo;
    }

}
